-- MySQL Script generated by MySQL Workbench
-- Mon Apr 25 22:48:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema c2_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema c2_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `c2_db` DEFAULT CHARACTER SET utf8 ;
USE `c2_db` ;

-- -----------------------------------------------------
-- Table `c2_db`.`hosts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c2_db`.`hosts` (
  `host_id` INT NOT NULL AUTO_INCREMENT,
  `hostname` VARCHAR(45) NULL,
  PRIMARY KEY (`host_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c2_db`.`commands_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c2_db`.`commands_history` (
  `cmd_id` INT NOT NULL AUTO_INCREMENT,
  `command` VARCHAR(512) NULL,
  `status` INT NULL,
  `answer` VARCHAR(1024) NULL,
  PRIMARY KEY (`cmd_id`),
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`cmd_id`)
    REFERENCES `c2_db`.`hosts` (`host_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
